#!/bin/sh
#
# @name Gazebo x500 depth modify
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_depth_modify}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# GNSS-denied cave flight defaults: fuse external vision and allow arming
# without GPS while keeping the rest of the x500 baseline unchanged.
param set EKF2_GPS_CTRL 0
param set EKF2_EV_CTRL 15
param set EKF2_HGT_REF 3
param set EKF2_MAG_TYPE 5
param set COM_ARM_WO_GPS 1
param set COM_DL_LOSS_T 10
param set NAV_DLL_ACT 0
param set SYS_HAS_MAG 0
